## Tensor:

All the data are represented as tensor in Tensorflow. It's similar to numpy.array in numpy.

A scalar is a o dimension tensor.

A vector is a 1 dimension tensor.

A matrix is a 2 dimension tensor.

A RGB image is a 3 dimension tensor.

...


In [1]:
import numpy as np
import tensorflow as tf

In [2]:
i = tf.constant(1)
l = tf.constant(1,dtype = tf.int64)
f = tf.constant(1.23)
d = tf.constant(3.14,dtype = tf.double)
s = tf.constant("hello world")
b = tf.constant(True)

In [4]:
## check data type in tf
print(i)
print(l)
print(f)
print(d)
print(s)
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1.23, shape=(), dtype=float32)
tf.Tensor(3.14, shape=(), dtype=float64)
tf.Tensor(b'hello world', shape=(), dtype=string)
tf.Tensor(True, shape=(), dtype=bool)


In [5]:
## check the dimension of a tensor

scalar = tf.constant(True)

print(scalar)
print(scalar.numpy())
print(scalar.numpy().ndim)

tf.Tensor(True, shape=(), dtype=bool)
True
0


In [6]:
## check the dimension of a tensor
## string is a bytes object, without dimension

scalar = tf.constant("hello")

print(scalar)
print(scalar.numpy())
print(scalar.numpy().ndim)

tf.Tensor(b'hello', shape=(), dtype=string)
b'hello'


AttributeError: 'bytes' object has no attribute 'ndim'

In [7]:
## check dimension of vector
vector = tf.constant([1.0,2.0,3.0,4.0])

print(tf.rank(vector))
print(np.ndim(vector.numpy()))

tf.Tensor(1, shape=(), dtype=int32)
1


In [8]:
## check dimension of matrix
matrix = tf.constant([[1.0,2.0],[3.0,4.0]])

print(tf.rank(matrix).numpy())
print(np.ndim(matrix))

2
2


In [9]:
## check 4 dimension/rank tensor
tensor4 = tf.constant([[[[1.0,1.0],[2.0,2.0]],[[3.0,3.0],[4.0,4.0]]],
                        [[[5.0,5.0],[6.0,6.0]],[[7.0,7.0],[8.0,8.0]]]])
print(tensor4)
print(tf.rank(tensor4))

tf.Tensor(
[[[[1. 1.]
   [2. 2.]]

  [[3. 3.]
   [4. 4.]]]


 [[[5. 5.]
   [6. 6.]]

  [[7. 7.]
   [8. 8.]]]], shape=(2, 2, 2, 2), dtype=float32)
tf.Tensor(4, shape=(), dtype=int32)


#### Variable vs constant

In [10]:
## value of tf.constant can't be changed
c = tf.constant([1.0,2.0])
print(c)
print(id(c))
c = c + tf.constant([1.0,1.0])
print(c)
print(id(c))

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
5229011184
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
5169440136


In [12]:
## value of tf.Variable can be changed by assign and assign_add function
v = tf.Variable([1.0,2.0],name = "v")
print(v)
print(id(v))
v.assign_add([1.0,1.0])
print(v)
print(id(v))

<tf.Variable 'v:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
4596289152
<tf.Variable 'v:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
4596289152


## Basic operation

### 1. Create a tensor

In [13]:
tf.constant([1,2,3], dtype=tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [14]:
tf.range(1, 10, delta = 2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [15]:
tf.linspace(0.0, 2*3.14, 100)

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.        , 0.06343435, 0.1268687 , 0.19030304, 0.2537374 ,
       0.31717175, 0.38060609, 0.44404042, 0.5074748 , 0.57090914,
       0.6343435 , 0.6977778 , 0.76121217, 0.82464653, 0.88808084,
       0.9515152 , 1.0149496 , 1.0783839 , 1.1418183 , 1.2052526 ,
       1.268687  , 1.3321213 , 1.3955556 , 1.45899   , 1.5224243 ,
       1.5858587 , 1.6492931 , 1.7127274 , 1.7761617 , 1.839596  ,
       1.9030304 , 1.9664648 , 2.0298991 , 2.0933335 , 2.1567678 ,
       2.2202022 , 2.2836366 , 2.347071  , 2.4105053 , 2.4739397 ,
       2.537374  , 2.6008081 , 2.6642425 , 2.7276769 , 2.7911112 ,
       2.8545456 , 2.91798   , 2.9814143 , 3.0448487 , 3.108283  ,
       3.1717174 , 3.2351518 , 3.2985861 , 3.3620205 , 3.4254549 ,
       3.4888892 , 3.5523233 , 3.6157577 , 3.679192  , 3.7426264 ,
       3.8060608 , 3.8694952 , 3.9329295 , 3.9963639 , 4.0597982 ,
       4.1232324 , 4.186667  , 4.250101  , 4.3135357 , 4.37697   ,
       4.44040

In [16]:
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [17]:
tf.zeros(3)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [18]:
tf.eye(5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [19]:
tf.ones([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [20]:
tf.zeros_like(tf.ones([3, 3]))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [21]:
tf.fill([4, 3], 2020)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[2020, 2020, 2020],
       [2020, 2020, 2020],
       [2020, 2020, 2020],
       [2020, 2020, 2020]], dtype=int32)>

In [22]:
tf.random.uniform([5], minval=10, maxval=100)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([26.256483, 84.28469 , 10.603668, 42.72337 , 67.596275],
      dtype=float32)>

In [23]:
tf.random.normal([4, 3], mean=10, stddev=2)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[11.657225 ,  9.213058 ,  9.692511 ],
       [ 8.578913 ,  7.5506835,  7.3791475],
       [13.595366 , 13.110031 , 10.09085  ],
       [ 9.001906 ,  6.7269964, 10.214141 ]], dtype=float32)>

In [25]:
tf.linalg.diag([1,2,3,4,5,6])

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]], dtype=int32)>

### 2. Tensor indexing

In [26]:
test = tf.random.uniform([5, 5], minval=0, maxval=10, dtype=tf.int32)

In [27]:
test

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 7, 2, 7, 4],
       [1, 9, 8, 1, 0],
       [4, 7, 0, 6, 3],
       [9, 3, 0, 2, 9],
       [2, 3, 9, 5, 1]], dtype=int32)>

In [28]:
## first row
tf.print(test[0])

[0 7 2 7 4]


In [29]:
## element in first row and third column
tf.print(test[0][2])

2


In [30]:
## element in first row and last column
tf.print(test[0][-1])

4


In [32]:
## elements from second line to fifth line and all columns
tf.print(test[1:4, :])

[[1 9 8 1 0]
 [4 7 0 6 3]
 [9 3 0 2 9]]


In [33]:
## elements in every 2 rows and every 2 columns from top-left
tf.print(test[::2, ::2])

[[0 2 4]
 [4 0 3]
 [2 9 1]]


In [34]:
tf.print(test[::3, ::3])

[[0 7]
 [9 2]]


#### Index assign for variable

In [35]:
var = tf.Variable([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
var

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [44]:
var[::2, ::2].assign(tf.constant([[1000, 10000], [1000, 10000]]))

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=int32, numpy=
array([[ 1000,     2, 10000],
       [    4,     5,     6],
       [ 1000,     8, 10000]], dtype=int32)>

#### Slicing for tensor

In [45]:
## suppose we have 4 classes and 10 students in one class. The scores for their 7 courses are stored in a tensor
scores = tf.random.uniform((4,10,7),minval=0,maxval=100,dtype=tf.int32)
scores

<tf.Tensor: shape=(4, 10, 7), dtype=int32, numpy=
array([[[65,  7, 34,  6, 52, 57, 57],
        [91, 85, 45, 12, 54, 86, 84],
        [25, 57, 74, 76, 66, 21,  1],
        [54, 99, 85, 47, 76, 67, 66],
        [23, 26, 22, 54, 40, 26, 36],
        [28,  5, 18, 60, 95, 52, 16],
        [ 3, 53, 39, 42, 82, 13, 67],
        [49, 57, 53, 97, 24, 77, 62],
        [19, 69, 87, 71, 99, 84, 25],
        [72, 44, 86, 80, 79, 93, 43]],

       [[24,  8, 33, 58, 31, 88, 40],
        [18, 95, 88, 31, 36, 12, 31],
        [67,  6, 15, 69, 87, 15,  4],
        [18, 18, 56, 11, 32,  9, 31],
        [92, 90, 45, 56, 10, 26, 98],
        [64, 58, 97, 43,  3,  9, 82],
        [13, 89, 17, 65, 20, 56, 72],
        [54,  6, 67, 82, 55, 86, 42],
        [77, 28, 61, 57,  7, 81,  9],
        [33, 35, 65,  6, 51, 17, 86]],

       [[ 8, 79, 18, 37, 71, 72, 84],
        [ 7, 32, 17, 31, 50, 90, 31],
        [11, 22, 85, 28, 77, 18, 71],
        [24, 92, 35, 96, 21, 87, 59],
        [89, 21,  1, 50, 44, 29, 9

In [48]:
# get the scores of first student and last student in every class
tf.gather(scores, [0, 9], axis=1)

<tf.Tensor: shape=(4, 2, 7), dtype=int32, numpy=
array([[[65,  7, 34,  6, 52, 57, 57],
        [72, 44, 86, 80, 79, 93, 43]],

       [[24,  8, 33, 58, 31, 88, 40],
        [33, 35, 65,  6, 51, 17, 86]],

       [[ 8, 79, 18, 37, 71, 72, 84],
        [88,  6,  1, 53, 39, 92, 89]],

       [[41, 75, 89, 63, 94, 92, 29],
        [81, 40, 36, 81, 26,  5,  8]]], dtype=int32)>

In [51]:
# get the scores of the first and last courses of the first and last student in every class
tf.gather(tf.gather(scores, [0, 9], axis=1), [0, 6], axis=2)

<tf.Tensor: shape=(4, 2, 2), dtype=int32, numpy=
array([[[65, 57],
        [72, 43]],

       [[24, 40],
        [33, 86]],

       [[ 8, 84],
        [88, 89]],

       [[41, 29],
        [81,  8]]], dtype=int32)>

Other frequently used functions:
tf.scatter, tf.where, tf.boolean_mast, etc.

### 3. Change the dimension of tensor

tf.reshape

tf.squeeze

tf.expand_dims

tf.transpose

In [52]:
a = tf.random.uniform(shape=[1,3,3,2],
                      minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)
tf.print(a)

TensorShape([1, 3, 3, 2])
[[[[184 229]
   [236 188]
   [115 78]]

  [[35 251]
   [125 36]
   [10 62]]

  [[185 85]
   [182 80]
   [236 239]]]]


In [53]:
tf.reshape(a,[3,6])

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[184, 229, 236, 188, 115,  78],
       [ 35, 251, 125,  36,  10,  62],
       [185,  85, 182,  80, 236, 239]], dtype=int32)>

In [54]:
tf.squeeze(a)

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[184, 229],
        [236, 188],
        [115,  78]],

       [[ 35, 251],
        [125,  36],
        [ 10,  62]],

       [[185,  85],
        [182,  80],
        [236, 239]]], dtype=int32)>

In [56]:
tf.expand_dims(a, axis=-1) 

<tf.Tensor: shape=(1, 3, 3, 2, 1), dtype=int32, numpy=
array([[[[[184],
          [229]],

         [[236],
          [188]],

         [[115],
          [ 78]]],


        [[[ 35],
          [251]],

         [[125],
          [ 36]],

         [[ 10],
          [ 62]]],


        [[[185],
          [ 85]],

         [[182],
          [ 80]],

         [[236],
          [239]]]]], dtype=int32)>

The operation tf.reshape, tf.expand_dims, tf.squeeze change only the logic dimension. How the data stored in the memory is not changed. So the 3 operation is very fast. However, the tf.tranpose changes the data store order and runs relatively slower.

### 4. Tensor concatenate and split

Similar to numpy, we have tf.concat, tf.stack, tf.split

In [57]:
## tf.concat does't add new dimension
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

tf.concat([a,b,c],axis = 0)

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>

In [58]:
## tf.stack adds new dimension
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

tf.stack([a,b,c],axis = 0)

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)>

In [59]:
tf.split(c, 3, axis = 0)

InvalidArgumentError: Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 2) and num_split 3 [Op:Split] name: split