## Math operation

In this notebook, I pratice the common math operation in Tensorflow. There are three kinds of operations:

1. Scalar operation
2. Vector operation
3. Matrix operation

At the end, we test the broadcasting in Tensorflow.

In [1]:
import numpy as np
import tensorflow as tf

## 1. Scalar operation

Scalar opertions includes: add, multiply, divide, sin/cos/tan, log, power, etc.

In [3]:
a = tf.constant(1)
b = tf.constant(2)

a+b

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
a-b

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [5]:
a*b

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [6]:
a/b

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

In [7]:
a**2

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [10]:
a% b

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [11]:
a//b

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [13]:
a>2

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [16]:
tf.sin(tf.cast(a, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.84147096>

In [17]:
## tf.sin requires float input
tf.sin(a)

NotFoundError: Could not find valid device for node.
Node:{{node Sin}}
All kernels registered for op Sin :
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
  device='XLA_CPU'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
 [Op:Sin]

In [18]:
tf.minimum(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

## 2. Vector operation

In [19]:
a = tf.range(1,10)
tf.print(tf.reduce_sum(a))
tf.print(tf.reduce_mean(a))
tf.print(tf.reduce_max(a))
tf.print(tf.reduce_min(a))
tf.print(tf.reduce_prod(a))

45
5
9
1
362880


In [20]:
p = tf.constant([True,False,False])
q = tf.constant([False,False,True])
tf.print(tf.reduce_all(p))
tf.print(tf.reduce_any(q))

0
1


In [21]:
## topk
a = tf.constant([1,3,7,5,4,8])

values,indices = tf.math.top_k(a,3,sorted=True)
tf.print(values)
tf.print(indices)

[8 7 5]
[5 2 3]


## 3. Matrix operation

Most of matrix operations are in tf.linalg

In [22]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[2,0],[0,2]])

In [23]:
## matmul

In [24]:
a@b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [25]:
tf.linalg.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [26]:
## matrix inverse, requires float
a = tf.constant([[1.0,2],[3.0,4]],dtype = tf.float32)
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [27]:
a = tf.constant([[1.0,2],[3,4]])
tf.linalg.trace(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [28]:
a = tf.constant([[1.0,2],[3,4]])
tf.linalg.norm(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.477226>

In [29]:
a = tf.constant([[1.0,2],[3,4]])
tf.linalg.det(a)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [30]:
tf.linalg.eigvalsh(a)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.8541021,  5.854102 ], dtype=float32)>

In [31]:
a  = tf.constant([[1.0,2.0],[3.0,4.0]],dtype = tf.float32)
q,r = tf.linalg.qr(a)
tf.print(q)
tf.print(r)
tf.print(q@r)

[[-0.316227794 -0.948683321]
 [-0.948683321 0.316227734]]
[[-3.1622777 -4.4271884]
 [0 -0.632455349]]
[[1.00000012 1.99999976]
 [3 4]]


In [32]:
a  = tf.constant([[1.0,2.0],[3.0,4.0]],dtype = tf.float32)
v,s,d = tf.linalg.svd(a)
tf.matmul(tf.matmul(s,tf.linalg.diag(v)),d)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.9999996, 1.9999996],
       [2.9999998, 4.       ]], dtype=float32)>

## 4. Broadcasting

Similar to numpy and python

In [33]:
a = tf.constant([1,2,3])
b = tf.constant([[0,0,0],[1,1,1],[2,2,2]])
b + a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]], dtype=int32)>

In [34]:
tf.broadcast_to(a,b.shape)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [35]:
tf.broadcast_static_shape(a.shape,b.shape)

TensorShape([3, 3])

In [36]:
c = tf.constant([1,2,3])
d = tf.constant([[1],[2],[3]])
tf.broadcast_dynamic_shape(tf.shape(c),tf.shape(d))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

In [37]:
c+d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]], dtype=int32)>